### ISSUE TITLE
Moving this to saltstack-formulas

### ISSUE THREAD

**Issue by alxwr** [saltstack-formulas/stunnel-formula#1]
@avandendorpe @opdude

Hi, is it OK for you if I move this forked formula over to saltstack-formulas?
I'd replace the (long, copyright-less) licence file with the standard SaltStack Apache2 license.

Alex

**Comment by avandendorpe** [comment]
@alxwr

Fine on my end - one of those things I never made time for.

**Comment by opdude** [comment]
@alxwr Fine by me :)

**Comment by alxwr** [comment]
Great, Thanks!
